== Lab: Finding a Bacon Number

ifdef::env-graphgist[]
// lesson 1 knows
//hide
//setup
[source, cypher]
----
CREATE (TheMatrix:Movie {title:'The Matrix', released:1999, tagline:'Welcome to the Real World'}) CREATE (Keanu:Person {name:'Keanu Reeves', born:1964}) CREATE (Carrie:Person {name:'Carrie-Anne Moss', born:1967}) CREATE (Laurence:Person {name:'Laurence Fishburne', born:1961}) CREATE (Hugo:Person {name:'Hugo Weaving', born:1960}) CREATE (AndyW:Person {name:'Andy Wachowski', born:1967}) CREATE (LanaW:Person {name:'Lana Wachowski', born:1965}) CREATE (JoelS:Person {name:'Joel Silver', born:1952}) CREATE   (Keanu)-[:ACTED_IN {roles:['Neo']}]->(TheMatrix),   (Carrie)-[:ACTED_IN {roles:['Trinity']}]->(TheMatrix),   (Laurence)-[:ACTED_IN {roles:['Morpheus']}]->(TheMatrix),   (Hugo)-[:ACTED_IN {roles:['Agent Smith']}]->(TheMatrix),   (AndyW)-[:DIRECTED]->(TheMatrix),   (LanaW)-[:DIRECTED]->(TheMatrix),   (JoelS)-[:PRODUCED]->(TheMatrix)   CREATE (TopGun:Movie {title:'Top Gun', released:1986, tagline:'I feel the need, the need for speed.'}) CREATE (TomC:Person {name:'Tom Cruise', born:1962}) CREATE (KellyM:Person {name:'Kelly McGillis', born:1957}) CREATE (ValK:Person {name:'Val Kilmer', born:1959}) CREATE (AnthonyE:Person {name:'Anthony Edwards', born:1962}) CREATE (TomS:Person {name:'Tom Skerritt', born:1933}) CREATE (MegR:Person {name:'Meg Ryan', born:1961}) CREATE (TonyS:Person {name:'Tony Scott', born:1944}) CREATE (JimC:Person {name:'Jim Cash', born:1941}) CREATE   (TomC)-[:ACTED_IN {roles:['Maverick']}]->(TopGun),   (KellyM)-[:ACTED_IN {roles:['Charlie']}]->(TopGun),   (ValK)-[:ACTED_IN {roles:['Iceman']}]->(TopGun),   (AnthonyE)-[:ACTED_IN {roles:['Goose']}]->(TopGun),   (TomS)-[:ACTED_IN {roles:['Viper']}]->(TopGun),   (MegR)-[:ACTED_IN {roles:['Carole']}]->(TopGun),   (TonyS)-[:DIRECTED]->(TopGun),   (JimC)-[:WROTE]->(TopGun)  CREATE (JerryMaguire:Movie {title:'Jerry Maguire', released:2000, tagline:'The rest of his life begins now.'}) CREATE (ReneeZ:Person {name:'Renee Zellweger', born:1969}) CREATE (KellyP:Person {name:'Kelly Preston', born:1962}) CREATE (JerryO:Person {name:'Jerry O\'Connell', born:1974}) CREATE (JayM:Person {name:'Jay Mohr', born:1970}) CREATE (BonnieH:Person {name:'Bonnie Hunt', born:1961}) CREATE (ReginaK:Person {name:'Regina King', born:1971}) CREATE (JonathanL:Person {name:'Jonathan Lipnicki', born:1990}) CREATE (CameronC:Person {name:'Cameron Crowe', born:1957}) CREATE (CubaG:Person {name:'Cuba Gooding Jr.', born:1968}) CREATE   (TomC)-[:ACTED_IN {roles:['Jerry Maguire']}]->(JerryMaguire),   (CubaG)-[:ACTED_IN {roles:['Rod Tidwell']}]->(JerryMaguire),   (ReneeZ)-[:ACTED_IN {roles:['Dorothy Boyd']}]->(JerryMaguire),   (KellyP)-[:ACTED_IN {roles:['Avery Bishop']}]->(JerryMaguire),   (JerryO)-[:ACTED_IN {roles:['Frank Cushman']}]->(JerryMaguire),   (JayM)-[:ACTED_IN {roles:['Bob Sugar']}]->(JerryMaguire),   (BonnieH)-[:ACTED_IN {roles:['Laurel Boyd']}]->(JerryMaguire),   (ReginaK)-[:ACTED_IN {roles:['Marcee Tidwell']}]->(JerryMaguire),   (JonathanL)-[:ACTED_IN {roles:['Ray Boyd']}]->(JerryMaguire),   (CameronC)-[:DIRECTED]->(JerryMaguire),   (CameronC)-[:PRODUCED]->(JerryMaguire),   (CameronC)-[:WROTE]->(JerryMaguire)   CREATE (TheReplacements:Movie {title:'The Replacements', released:2000, tagline:'Pain heals, Chicks dig scars... Glory lasts forever'}) CREATE (Brooke:Person {name:'Brooke Langton', born:1970}) CREATE (Gene:Person {name:'Gene Hackman', born:1930}) CREATE (Orlando:Person {name:'Orlando Jones', born:1968}) CREATE (Howard:Person {name:'Howard Deutch', born:1950}) CREATE   (Keanu)-[:ACTED_IN {roles:['Shane Falco']}]->(TheReplacements),   (Brooke)-[:ACTED_IN {roles:['Annabelle Farrell']}]->(TheReplacements),   (Gene)-[:ACTED_IN {roles:['Jimmy McGinty']}]->(TheReplacements),   (Orlando)-[:ACTED_IN {roles:['Clifford Franklin']}]->(TheReplacements),   (Howard)-[:DIRECTED]->(TheReplacements)  CREATE (TheBirdcage:Movie {title:'The Birdcage', released:1996, tagline:'Come as you are'}) CREATE (MikeN:Person {name:'Mike Nichols', born:1931}) CREATE (Nathan:Person {name:'Nathan Lane', born:1956}) CREATE (Robin:Person {name:'Robin Williams', born:1951}) CREATE   (Robin)-[:ACTED_IN {roles:['Armand Goldman']}]->(TheBirdcage),   (Nathan)-[:ACTED_IN {roles:['Albert Goldman']}]->(TheBirdcage),   (Gene)-[:ACTED_IN {roles:['Sen. Kevin Keeley']}]->(TheBirdcage),   (MikeN)-[:DIRECTED]->(TheBirdcage)  CREATE (Unforgiven:Movie {title:'Unforgiven', released:1992, tagline:'it\'s a hell of a thing, killing a man'}) CREATE (RichardH:Person {name:'Richard Harris', born:1930}) CREATE (ClintE:Person {name:'Clint Eastwood', born:1930}) CREATE   (RichardH)-[:ACTED_IN {roles:['English Bob']}]->(Unforgiven),   (ClintE)-[:ACTED_IN {roles:['Bill Munny']}]->(Unforgiven),   (Gene)-[:ACTED_IN {roles:['Little Bill Daggett']}]->(Unforgiven),   (ClintE)-[:DIRECTED]->(Unforgiven)  CREATE (CloudAtlas:Movie {title:'Cloud Atlas', released:2012, tagline:'Everything is connected'}) CREATE (TomH:Person {name:'Tom Hanks', born:1956}) CREATE (HalleB:Person {name:'Halle Berry', born:1966}) CREATE (JimB:Person {name:'Jim Broadbent', born:1949}) CREATE (TomT:Person {name:'Tom Tykwer', born:1965}) CREATE   (TomH)-[:ACTED_IN {roles:['Zachry', 'Dr. Henry Goose', 'Isaac Sachs', 'Dermot Hoggins']}]->(CloudAtlas),   (Hugo)-[:ACTED_IN {roles:['Bill Smoke', 'Haskell Moore', 'Tadeusz Kesselring', 'Nurse Noakes', 'Boardman Mephi', 'Old Georgie']}]->(CloudAtlas),   (HalleB)-[:ACTED_IN {roles:['Luisa Rey', 'Jocasta Ayrs', 'Ovid', 'Meronym']}]->(CloudAtlas),   (JimB)-[:ACTED_IN {roles:['Vyvyan Ayrs', 'Captain Molyneux', 'Timothy Cavendish']}]->(CloudAtlas),   (TomT)-[:DIRECTED]->(CloudAtlas),   (AndyW)-[:DIRECTED]->(CloudAtlas),   (LanaW)-[:DIRECTED]->(CloudAtlas)  CREATE (AFewGoodMen:Movie {title:'A Few Good Men', released:1992, tagline:'In the heart of the nation\'s capital, in a courthouse of the U.S. government, one man will stop at nothing to keep his honor, and one will stop at nothing to find the truth.'}) CREATE (JackN:Person {name:'Jack Nicholson', born:1937}) CREATE (DemiM:Person {name:'Demi Moore', born:1962}) CREATE (KevinB:Person {name:'Kevin Bacon', born:1958}) CREATE (KieferS:Person {name:'Kiefer Sutherland', born:1966}) CREATE (NoahW:Person {name:'Noah Wyle', born:1971}) CREATE (KevinP:Person {name:'Kevin Pollak', born:1957}) CREATE (JTW:Person {name:'J.T. Walsh', born:1943}) CREATE (JamesM:Person {name:'James Marshall', born:1967}) CREATE (ChristopherG:Person {name:'Christopher Guest', born:1948}) CREATE (RobR:Person {name:'Rob Reiner', born:1947}) CREATE (AaronS:Person {name:'Aaron Sorkin', born:1961}) CREATE   (TomC)-[:ACTED_IN {roles:['Lt. Daniel Kaffee']}]->(AFewGoodMen),   (JackN)-[:ACTED_IN {roles:['Col. Nathan R. Jessup']}]->(AFewGoodMen),   (DemiM)-[:ACTED_IN {roles:['Lt. Cdr. JoAnne Galloway']}]->(AFewGoodMen),   (KevinB)-[:ACTED_IN {roles:['Capt. Jack Ross']}]->(AFewGoodMen),   (KieferS)-[:ACTED_IN {roles:['Lt. Jonathan Kendrick']}]->(AFewGoodMen),   (NoahW)-[:ACTED_IN {roles:['Cpl. Jeffrey Barnes']}]->(AFewGoodMen),   (CubaG)-[:ACTED_IN {roles:['Cpl. Carl Hammaker']}]->(AFewGoodMen),   (KevinP)-[:ACTED_IN {roles:['Lt. Sam Weinberg']}]->(AFewGoodMen),   (JTW)-[:ACTED_IN {roles:['Lt. Col. Matthew Andrew Markinson']}]->(AFewGoodMen),   (JamesM)-[:ACTED_IN {roles:['Pfc. Louden Downey']}]->(AFewGoodMen),   (ChristopherG)-[:ACTED_IN {roles:['Dr. Stone']}]->(AFewGoodMen),   (AaronS)-[:ACTED_IN {roles:['Man in Bar']}]->(AFewGoodMen),   (RobR)-[:DIRECTED]->(AFewGoodMen),   (AaronS)-[:WROTE]->(AFewGoodMen)  CREATE (Apollo13:Movie {title:'Apollo 13', released:1995, tagline:'Houston, we have a problem.'}) CREATE (EdH:Person {name:'Ed Harris', born:1950}) CREATE (BillPax:Person {name:'Bill Paxton', born:1955}) CREATE (RonH:Person {name:'Ron Howard', born:1954}) CREATE (GaryS:Person {name:'Gary Sinise', born:1955}) CREATE   (TomH)-[:ACTED_IN {roles:['Jim Lovell']}]->(Apollo13),   (KevinB)-[:ACTED_IN {roles:['Jack Swigert']}]->(Apollo13),   (EdH)-[:ACTED_IN {roles:['Gene Kranz']}]->(Apollo13),   (BillPax)-[:ACTED_IN {roles:['Fred Haise']}]->(Apollo13),   (GaryS)-[:ACTED_IN {roles:['Ken Mattingly']}]->(Apollo13),   (RonH)-[:DIRECTED]->(Apollo13) WITH TheMatrix MATCH (n:Person)-[:ACTED_IN|DIRECTED]->()<-[:ACTED_IN|DIRECTED]-(movie) WHERE NOT (n)-[:KNOWS]-(movie) MERGE (n)-[:KNOWS]->(movie)
----
endif::[]

==== What is a Bacon Number?

The _Bacon Number_ is an amalgam of the concepts of the _Bacon Path_ and the _Erdös number_. An individual's Bacon Number is the number of nodes necessary to reach Kevin Bacon in a relationship graph.

For example, if the relationship is `KNOWS`, then anyone who has acted with Kevin in a film is likely to have a Bacon Number of 1.
If actor A has acted with actor B, who has acted with Kevin Bacon, but actor A has not acted with Kevin Bacon, the Bacon Number of actor A is 2.
Kevin Bacon himself has a Bacon Number of 0.
Actors who have absolutely no connection to Kevin Bacon have infinite Bacon Numbers.

==== Find the Bacon Number for Keanu Reeves

The `shortestPath()` function can help you.
It returns paths, much like a normal graph pattern in `MATCH`, just the shortest ones.
You would use it like this:

[source, cypher]
----
MATCH p=shortestPath( (node1)-[*]-(node2) )
RETURN length(person), nodes(person)
----
//table

So in our case, we have to find both `Keanu Reeves` and `Kevin Bacon` and use our `KNOWS` relationships to find the shortest paths between them.

[source, cypher]
----
MATCH p=shortestPath((keanu:Person)-[:KNOWS*]-(kevin:Person))
WHERE keanu.name="Keanu Reeves" and kevin.name = "Kevin Bacon"
RETURN length(person)
----
//table

Or in an alternative variant, where we find the two end-nodes first and then the shortest path:

[source, cypher]
----
MATCH (keanu:Person {name:"Keanu Reeves"}),
(kevin:Person {name:"Kevin Bacon"})
MATCH p=shortestPath((keanu)-[:KNOWS*]->(kevin))
RETURN length(person);
----
//table

=== What people join Keanu to Kevin?

We use one of our collection functions for this.
For more details, see the {manual-cypher}#cypher-refcard[Cypher Reference card] and the http://neo4j.com/docs/stable/syntax-collections[Cypher Manual] on these functions.

As we've learned, a path is a string of nodes interspersed with relationships.
We can access the collection of nodes with `nodes(path)`.
The collection function we want to use is `extract`, which runs an expression on each element of a collection and returns that resulting value instead of the element.
The syntax is: `extract( x in coll | expr )`

For example:

* `extract(x in [1,2,3] | x*x)` to return the squares of a list, or

* `extract(n in nodes(path) | n.name)` to return the names of the nodes in a list

* a shorthand for extract is `[ x in coll | expr ]`

Let's give it a try:

[source, cypher]
----
MATCH (keanu:Person {name:"Keanu Reeves"}),
 (kevin:Person {name:"Kevin Bacon"})
MATCH p=shortestPath((keanu)-[:KNOWS*]->(kevin))
RETURN [ n in nodes(person) | n.name ];
----
//table

Fold out the tabular result below to see all elements of the collection, i.e. all names on the path.

If you wanted to skip the first and last name, you could use a subscript on the collection like `[2..5]`, or in our case `[1..-1]`, which means everything from the second to the before last element.

[source, cypher]
----
MATCH (keanu:Person {name:"Keanu Reeves"}),
  (kevin:Person {name:"Kevin Bacon"})
MATCH p=shortestPath((keanu)-[:KNOWS*]->(kevin))
RETURN [ n in nodes(person)[1..-1] | n.name ];
----

//TODO-WIDGET - section is not in training
ifndef::env-graphgist[]
++++
<div id="default"></div>
++++
endif::env-graphgist[]

//console

=== Bacon Number and Shortest Path Resources

* {manual-cypher}/clauses/match[Match^]
* {manual-cypher}/clauses/return[Return^]
* {manual-cypher}/clauses/where[Where^]
* {manual-cypher}/clauses/match/#query-shortest-path[Shortest Path^]
