= Forcing queries to use indexes
:icons: font

== Forcing queries to use indexes

Let's import the full movies dataset

[source, cypher, subs=attributes]
----
LOAD CSV WITH HEADERS FROM '{csv-url}people.csv' as row
MERGE(person:Person {id: toInt(row.personId)})
ON CREATE SET person.name = row.name,
              person.born = toInt(row.birthYear),
              person.died = toInt(row.deathYear)
----

LOAD CSV WITH HEADERS FROM 'file:///Users/markneedham/projects/graphconnect-training/new_movies.csv' as record
WITH toInt(record.movieId) as movieId,
     record.title as title,
     toFloat(record.avgVote) as avgVote,
     toInt(record.releaseYear) as releaseYear,
     record.tagline as tagline,
     split(record.genres, ":") as genres
MERGE (movie:Movie {id:movieId})
ON CREATE SET
  movie.title = title,
  movie.avgVote = avgVote,
  movie.releaseYear = releaseYear,
  movie.tagline = tagline,
  movie.genres = genres;

LOAD CSV WITH HEADERS FROM 'file:///Users/markneedham/projects/graphconnect-training/directors.csv' as record
WITH toInt(record.movieId) as movieId, toInt(record.personId) as personId
MATCH (movie:Movie {id:movieId})
MATCH (person:Person {id: personId})
MERGE (person)-[:DIRECTED]->(movie);

LOAD CSV WITH HEADERS FROM 'file:///Users/markneedham/projects/graphconnect-training/actors.csv' as record
WITH toInt(record.movieId) as movieId,
     toInt(record.personId) as personId,
    CASE WHEN record.characters IS NULL then [] ELSE split(record.characters, ":") END as roles
MATCH (movie:Movie {id:movieId})
MATCH (person:Person {id: personId})
MERGE (person)-[:ACTED_IN {roles:roles}]->(movie);
----

In this section we're going to look at how we can
