== Neo4j Data Science Training

=== Overview

This course has 3 modules.  The first module (GoT in Neo4j Browser) and the last module (Legis Graph in Sandbox) can be taught indpendently.  The second module, on Jupyter Notebooks, requires data created in the first module.

=== Neo4j Browser: Game of Thrones Interaction Graph

Dataset: Interaction of Characters in the book series

Download and install Neo4j: http://neo4j.com/download/other-releases (best Neo4j Desktop: 0.5.0 (or later)

Download Neo4j Graph Algorithmms (jar): https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases/tag/3.2.5.2

Download APOC Procedures (jar) for your appropriate version from: https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases

Put these jars into your `$NEO4J_HOME/plugins`

Add this to `NEO4J_HOME/conf/neo4j.conf`:

`+dbms.security.procedures.unrestricted=algo.*,apoc.*+`

(We do the actual install in the class / guide)

Neo4j Browser Guide: `:play data_science`


=== Jupyter Notebooks: Game of Thrones Interaction Graph

Pre-requisite: Section 1 (above) to create the data required by this section

We have Jupyter notebooks for the session as well. You'll need to install neo4j-driver, pandas, mathplotlib, scikit-learn

```
pip install -r requirements.txt
```

* https://github.com/neo4j-contrib/training/blob/master/data_science/EDA.ipynb[Exploratory Data Analyis]
* https://github.com/neo4j-contrib/training/blob/master/data_science/AppliedGraphAlgorithms.ipynb[Applied Graph Algorithms]
* https://github.com/neo4j-contrib/training/blob/master/data_science/MachineLearning.ipynb[Machine Learning]

=== Neo4j Sandbox: Legis Graph

Pre-requisite: None

* Neo4j Sandbox `http://neo4j.com/sandbox` -> Legis Graph
* Neo4j Browser Guide `:play http://guides.neo4j.com/sandbox/legis-graph`
