= Multiple Models
:icons: font

== Multiple Models

During some of our refactoring queries we didn't 

Multiple models

You have to control the invariant from your application.
e.g. if an airline decides to cancel

Maybe this can be a slide based section?

What if we have multiple query patterns that we need to satisfy?

e.g. the model with dates in between `:Airport` and `AirportDay` is very optimised for finding flights on a specific date but it doesn't work so well if we want to search across multiple dates

Find me all the flights between <origin> and <destination> on <date>

vs

Find me all the flights between <origin> and <destination on <date1> or <date2> or <date3>

With that second version our query becomes a bit more maintainable if we have the `HAS_DAY` relationship although it would still be slower.



Which date will make it easier to filter?
Should I load in all the flights for two of the hubs and have those in another CSV file?

Hmm multiple CSV files.

Our model looks good so far but let's import some more data and see how it fares as we add more queries.

We need to import some more of the dataset in so we can see the problem with dense nodes

It’s not a bad model, but we will have very dense nodes. Think about major hubs like Atlanta, Beijing, Dubai, London Heathrow, or even my local Chicago O’Hare. These would be very massive nodes with no quick way to filter routes without checking multiple properties which will slow our traversal down quite a bit.

When a user is trying to book a flight, they know where they are starting from, where they want to go, and what day they want to fly. So lets reimagine our model to introduce the concept of days.


As a user I want to book a flight from <origin> to <destination> on <date>



(airport)-[:HAS_DAY]->(airportDay)-[:HAS_FLIGHT]->(flight)

== Exercise

We want to introduce the concept of an `Airline` so that we can quickly find fights by our favorite airline without having to scan through all the flights.
Don't forget to connect the `Airline` nodes to the appropriate flights.

== Answer: Create `Airline` nodes

[source, cypher]
----
MATCH (flight:Flight)
MERGE (airline:Airline {code: flight.airline})
MERGE (flight)-[:AIRLINE]->(airline)
----

We can make this even faster by forcing the use of indexes on both sides, but this seems like more of a solution for advanced Cypher than for modelling.

[source, cypher]
----
PROFILE
MATCH (origin:Airport {code: "LAS"})-[:`2008-1-30`]->(:AirportDay)<-[:ORIGIN]-(flight:Flight),
      (flight)-[:DESTINATION]->(:AirportDay)<-[:`2008-1-30`]-(destination:Airport {code: "MDW"})
USING INDEX origin:Airport(code)
USING INDEX destination:Airport(code)
RETURN *
----

== Other ideas

We could even connect the different legs of the flight together?

Other modeling topics:

* Inferred relationships
* Maintaining multiple models for optimal write speed

== Reload all the data vs refactoring

What do you think?
Should we bother with this careful refactoring or should we just load all our data from scratch?

== Next

pass:a[<a play-topic='{guides}/06_specific_relationship_types.html'>Specific Relationship Types</a>]
